# NumPy Arrays vs Python Lists

In [30]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
import numpy as np
import time

**Performance Comparison**

In [4]:
# Execution performanse

size = 10_000_000 # large data set of 10 million numbers.

# Python Lists
python_list = list(range(size))
start = time.time()

list_squared = [x**2 for x in python_list] # square of all nums.

end = time.time()
print("Python list time:", end - start, "seconds")

# NumPy Arrays
np_array = np.array(python_list)
start = time.time()

array_squared = np_array**2 # Vectorized operation
end = time.time()

print("NumPy array time:", end - start, "seconds")

Python list time: 1.6356201171875 seconds
NumPy array time: 0.03869819641113281 seconds


**Memory Usage Comparison**

In [5]:
# Memory Usage Comparison
import sys

print("Python List size:", sys.getsizeof(python_list) * len(python_list))
print("NumPy Array size:", np_array.nbytes)

Python List size: 800000560000000
NumPy Array size: 80000000


**Creating NumPy Arrays**
* There are multiple ways of creating NumPy arrays, most common of which are...

**01). From Python List**

In [6]:
#Creating NumPy Arrays - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)


In [7]:
arr2 = np.array([1, 2, 3, 4, "prime", 3.14])
print(arr2, type(arr2), arr2.shape)

['1' '2' '3' '4' 'prime' '3.14'] <class 'numpy.ndarray'> (6,)


In [8]:
arr3 = np.array([[1, 2, 3], [2, 3, 4], [5, 6, 7]])
print(arr3, type(arr3), arr3.shape)

[[1 2 3]
 [2 3 4]
 [5 6 7]] <class 'numpy.ndarray'> (3, 3)


**02). Using built-in Functions**
* Creating NumPy Arrays - from scratch

In [9]:
#01. zeros():- Saare elements 0 banata hai.

arr1 = np.zeros((3, 4), dtype = "int64") # 3x4 array of 0s
print(arr1, arr1.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)


In [10]:
#02. ones():- Saare elements 1 banata hai.

arr2 = np.ones((3, 3)) # 3x3 array of 1s
print(arr2, arr2.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)


In [11]:
#03. eye() function:- NumPy me Identity Matrix banane ke liye use hota hai.

arr3 = np.eye((3), dtype = "int64")
print(arr3, arr3.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)


In [12]:
#04. full() function NumPy me array ko kisi specific value se fill karne ke liye use hota hai.

arr4 = np.full((2, 3), 5)
print(arr4, arr4.shape)

[[5 5 5]
 [5 5 5]] (2, 3)


In [13]:
#05. arange():- Range create karta hai.

arr5 = np.arange(1, 20, 2)
print(arr5, arr5.shape)

[ 1  3  5  7  9 11 13 15 17 19] (10,)


In [14]:
#06. linspace():- Equal spacing values create karta hai.

arr6 = np.linspace(0, 10, 5)
print(arr6, arr6.shape)

[ 0.   2.5  5.   7.5 10. ] (5,)


In [15]:
#07. reshape():- Shape change karta hai.

a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)

print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
#08. 7. sum():- Sab values ka total.

a = np.array([1,2,3])

print(np.sum(a))

6


In [17]:
#09. mean():- Average nikalta hai.

a = np.array([10,20,30])

print(np.mean(a))

20.0


In [18]:
#10. max() and min():- Largest aur smallest value.

a = np.array([5,2,9,1])

print(np.max(a))
print(np.min(a))

9
1


In [19]:
#11. sqrt():- Square root nikalta hai.

a = np.array([1,4,9,16])

print(np.sqrt(a))

[1. 2. 3. 4.]


In [20]:
#12. random.rand():- Random numbers generate karta hai.

a = np.random.rand(3)

print(a)

[0.06722027 0.90363215 0.91520803]


In [21]:
#13. unique():- Duplicate values hata deta hai.

a = np.array([1,2,2,3,3,4])

print(np.unique(a))

[1 2 3 4]


# NumPy Array Properties
**Array Properties**:-Helps you understand and manipilate data in arrays efficiently...

In [22]:
# Useful Attributes

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(arr.shape) # Dimensions - (4 x 3)
print(arr.size)  # Total elements - (12)
print(arr.ndim)  # Number of dimensions - 2
print(arr.dtype) # Data type object - int64
print(arr.itemsize) #Size of each element in bytes - 8 for int64

(4, 3)
12
2
int64
8


* We can also exolicitly change the dtype for our arrays...

In [23]:
# Specific dtype at creation
str_arr = np.array([1, 2, 3], dtype = "U")
print(str_arr, str_arr.dtype)

float_arr = np.array([1, 2, 3], dtype = "float64")
print(float_arr, float_arr.dtype)

#Creating new array with a specific type from existing array
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)

['1' '2' '3'] <U1
[1. 2. 3.] float64
[1 2 3] int64


# Operations on Arrays
**There are a lot of useful operations that we can perform on our arrays...**

**01). Reshaping**

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2)) # convers (1x6) => (2x3)
print(reshaped, reshaped.shape)

flattened = reshaped.flatten() # convers 2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


**02). Indexing**

In [25]:
# Indexing for 1D array
arr = np.array([1, 2, 3, 4, 5])
print(arr[0]) # 1

1


In [26]:
# Indexing for 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr[0][1]) # 2
print(arr[1][2]) # 6

2
6


**03). Fancy Indexing**:-means accessing array elements using integer arrays/list of indices rather than plain slices
* Apart from simple indexing, we can also use Fancy & Boolean indexing...

In [27]:
# Fancy Indexing 
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 4]
print(arr[idx]) # print nums at given indices

[1 2 5]


**04). Boolean masking(or indexing)**:- means using a Boolean array (True/False) to select elements from another array...

In [28]:
# Boolean Indexing 
print(arr[arr > 2])      # print nums greater than 2
print(arr[arr % 2 == 0]) # print even nums

[3 4 5]
[2 4]


**05). Slicing**

In [29]:
# Slicing 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) # [3, 4, 5, 6]
print(arr[:6])  # [1, 2, 3, 4, 5, 6]
print(arr[3:])  # [4, 5, 6, 7]
print(arr[::2]) # [1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]


**Copy v/s View**:-Slicing a list returns a copy but slicing a NumPy array returns a view - for efficiency, View is like a shallow copy that shares the same sata as the original array, so no duplication happens here.
* Views are fast and memory-efficient (no data duplication).
* Copies are safe but slower and use more memory.

In [32]:
# Slice List is a COPY
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] # [2, 3, 4]
copy_list[1] = 333

print(copy_list)
print(py_list) # [1, 2, 3, 4, 5] - remains same

[2, 333, 4]
[1, 2, 3, 4, 5]


In [34]:
# Sliced Array is a VIEW
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] # [2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr) # [1, 2, 333, 4, 5] - changes

[  2 333   4]
[  1   2 333   4   5]


In [36]:
# Creating a COPY for Array
copy_arr = np_arr[1:4].copy() # [2, 3, 4]
copy_arr[2] = 444

print(copy_arr)
print(np_arr) # [1, 2, 3, 4, 5] - ramains same

[  2 333 444]
[  1   2 333   4   5]
